### PR TITLE
Updated Some Files

### PR DESCRIPTION
**Pull request by AlphaT3ch**
added some stuff on copyrights grammar and added some GitHub repo advertisements.

### CODE REVIEW

**Comment by maor322** [comment]
It's good. Nice. It makes more sence.

**Comment by 8JeDaYoshi8** [comment]
*sense

2015-05-13 17:19 GMT-04:30, maor322 <notifications@github.com>:

**Comment by StarLand64** [comment]
My English is too worsa to see the difference...

**Comment by 8JeDaYoshi8** [comment]
s/worsa/horrible
(?)

2015-05-15 4:41 GMT-04:30, StarLand <notifications@github.com>:

**Comment by AlphaT3ch** [comment]
@8JeDaYoshi8: Actually it would be "bad," Mr. English-Know-It-All, and yes the comma is inside of the quote as that is how grammar follows in the English language. Also English is uppercase as stated in the English Dictionary. Thank you for attending "English Time" with AlphaTech.

**Comment by 8JeDaYoshi8** [comment]
Eh, sorry.
But, Mr. English-Know-It-All???

YOU OFFENDED ME WITH YOUR WORDS.

2015-05-17 0:21 GMT-04:30, AlphaTech <notifications@github.com>:

**Pull request merged**
